backend:
  name: github
  repo: lpoulter/axiom-design-docs
  open_authoring: true

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: /assets

collections:
  - label: "Parent Components"
    name: "parent_components"
    folder: "content/parent_components"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Parent Name", name: "parent_name",  widget: "string" }
  - name: pages
    label: "Page"
    folder: "content/pages"
    create: true
    slug: "{{component_name}}"
    fields:
      - { label: "post_type", name: "post_type", widget: "hidden", default: "page" }
      - { label: "Parent Component", name: "parent_component", widget: "relation", default: "none", multiple: false, collection: "parent_components", searchFields: ["parent_name"], valueField: "parent_name",  display_fields: ["parent_name"], required: false }
      - { label: "Component Name", name: "component_name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Short Introduction", name: "main_introduction", widget: "string" }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - label: 'Page Section'
        name: 'sections'
        widget: 'list'
        types:
          - label: 'Block List'
            name: 'block_list'
            widget: object
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Section Introduction, name: section_introduction, widget: string, required: false }
              - label: 'Blocks'
                name: blocks
                widget: list
                fields:
                  - { label: Title, name: title, widget: string, required: false }
                  - { label: Text, name: text, widget: markdown, required: false }
                  - { label: Text Align, name: align, widget: select, default: right, options: [left, right]}
                  - { label: "Image", name: "image", widget: "image", required: false }
                  - { label: Image Width, name: imageWidth, widget: select, default: half, options: ["full", "half"]}
                  - { label: Image Description, name: alt, widget: string, required: false }
