backend:
  name: github
  repo: lpoulter/axiom-design-docs
  open_authoring: true

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: "Page"
    folder: "content/pages"
    create: true
    slug: "{{component_name}}"
    fields:
      - { label: "post_type", name: "post_type", widget: "hidden", default: "page" }
      - { label: "Component Name", name: "component_name", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Short Introduction", name: "main_introduction", widget: "string" }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - label: 'Page Section'
        name: 'sections'
        widget: 'list'
        types:
          - label: 'Block List'
            name: 'block_list'
            widget: object
            fields:
              - { label: Title, name: title, widget: string, required: false }
              - { label: Section Introduction, name: section_introduction, widget: string, required: false }
              - label: 'Blocks'
                name: blocks
                widget: list
                fields:
                  - { label: Title, name: title, widget: string, required: false }
                  - { label: Text, name: text, widget: markdown, required: false }
                  - { label: Text Align, name: align, widget: select, default: right, options: [left, right]}
                  - { label: "Image", name: "image", widget: "image", required: false }
                  - { label: Image Description, name: alt, widget: string, required: false }
